<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorRepository extends EntityRepository
{
	/**
	 * Find sensors with intermittent readings or low batteries
	 *
	 * @return array
	 */
	public function findSensorWarnings()
	{
		$datetime = new \DateTime;
		$datetime->modify('-3 minutes');

		$queryBuilder = $this->createQueryBuilder('sensor');
		$queryBuilder->addSelect('sensor')
			->andWhere('(sensor.datetime < :datetime) OR sensor.battery < :battery')
			->setParameter('datetime', $datetime)
			->setParameter('battery', 10.00)
			->addOrderBy('sensor.datetime', 'ASC')
			->addOrderBy('sensor.battery', 'ASC');
		return $queryBuilder->getQuery()->getResult();
	}
}
