app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@UserBundle/Resources/config/routing/all.yml"