security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path: /
            logout: true
            anonymous: true

    access_control:
        - { path: ^/(login(_check)?|wachtwoord-vergeten|registreren), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/wachtwoord-vergeten, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }

    access_decision_manager:
        strategy: affirmative