# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.service.latest_reading:
        class: AppBundle\Service\LatestReadingService
        arguments: ['@doctrine.orm.entity_manager']